url: https://test-stand.gb.ru/gateway/login
address: https://test-stand.gb.ru/api/posts
address_post: https://test-stand.gb.ru/gateway/posts

login: ivan111123
pswd: a7f1b97d65

title: new_titl
description: new_description
content: dfgjdgj fg df jddfgjdgjdgfjdgjgdgjj j  dgfjdgjdfgjdgjgjf  dgjjggjgj  fgjgfjgfjfg  fgj fgj